package com.iwebcoding.mobile.tool.constant.nls;

public interface AppViewNLS {
	String INIT_APPVIEW = "INIT_APPVIEW";
	String TITLE_APPVIEW = "TITLE_APPVIEW";
	String TITLE_TAB_JVIEWER = "TITLE_TAB_JVIEWER";
	String TITLE_TAB_GENCHKSUM = "TITLE_TAB_GENCHKSUM";
	String TITLE_TAB_DEPLOY = "TITLE_TAB_DEPLOY";
	
	String MENU_SYS = "MENU_SYS";
	String MENU_HELP = "MENU_HELP";
	String MENU_ABOUT = "MENU_ABOUT";
	String MENU_SYS_CFG = "MENU_SYS_CFG";
	String MENU_SYS_EXIT = "MENU_SYS_EXIT";
	String MENU_HELP_GUIDE = "MENU_HELP_GUIDE";
	String MENU_ABOUT_CONTACT = "MENU_ABOUT_CONTACT";
	
	String MSG_WELCOM = "MSG_WELCOME";
	String MSG_COPYRIGHT = "MSG_COPYRIGHT";
}
