package com.iwebcoding.mobile.tool.constant.nls;

public interface ChksumNLS {
	String TOOLTIP_CLEAR = "TOOLTIP_CLEAR";
	String TOOLTIP_COPY = "TOOLTIP_COPY";
	
	String RADIO_GENERATE_CHKSUM = "RADIO_GENERATE_CHKSUM";
	String RADIO_REPLACE_CHKSUM = "RADIO_REPLACE_CHKSUM";
	
	String BORDER_CHKSUM_MANAGE = "BORDER_CHKSUM_MANAGE";
	String BORDER_CONSOLE = "BORDER_CONSOLE";
	
	String TXT_FILE_FIELD = "TXT_FILE_FIELD";
	String CHOOSE_FILE = "CHOOSE_FILE";
	String BROWSE_FILE = "BROWSE_FILE";
	String BTN_GENERATE = "BTN_GENERATE";
	String REPLACE_PROGRESS = "REPLACE_PROGRESS";
	String BACKUP_JSON = "BACKUP_JSON";
	String REPLACE_JSON = "REPLACE_JSON";
	
	String REPORT_ZIPURL = "REPORT_ZIPURL";
	String REPORT_HASHCODE = "REPORT_HASHCODE";
	String REPORT_FILESIZE = "REPORT_FILESIZE";
	
	String PREREQ_CHECK = "PREREQ_CHECK";
	String PREREQ_STEP1 = "PREREQ_STEP1";
	String PREREQ_STEP2 = "PREREQ_STEP2";
	String PREREQ_CHECK_PASSED = "PREREQ_CHECK_PASSED";
	String PREREQ_CHECK_FAILED = "PREREQ_CHECK_FAILED";
	
	String MSG_MISS_ZIP = "MSG_MISS_ZIP";
	String MSG_FIND_ZIP = "MSG_FIND_ZIP";
	String MSG_VALIDATE = "MSG_VALIDATE";
	String MSG_NO_JSON_FILE = "MSG_NO_JSON_FILE";
	String MSG_CHKSUM_REPLACED = "MSG_CHKSUM_REPLACED";
	String MSG_REPLACE_PASSED = "MSG_REPLACE_PASSED";
	String MSG_REPLACE_FAILED = "MSG_REPLACE_FAILED";
	
	String LABEL_FILE_NAME = "LABEL_FILE_NAME";
	String LABEL_ZIP_FILE = "LABEL_ZIP_FILE";
	String LABEL_BACKUP_FILE = "LABEL_BACKUP_FILE";
}
