package com.iwebcoding.mobile.tool.constant.nls;

public interface DeployNLS {
	String BORDER_DEPLOY_MANAGE = "BORDER_DEPLOY_MANAGE";
	String BORDER_CONSOLE = "BORDER_CONSOLE";
	String BORDER_SETTING = "BORDER_SETTING";
	
	String LABEL_DEPLOY_ROOT = "LABEL_DEPLOY_ROOT";
	String LABEL_SERVER = "LABEL_SERVER";
	String LABEL_FILE = "LABEL_FILE";
	String LABEL_BTN_BROWSE = "LABEL_BTN_BROWSE";
	String LABEL_BTN_UPLOAD = "LABEL_BTN_UPLOAD";
	String LABEL_BTN_DEPLY_ROOT = "LABEL_BTN_DEPLY_ROOT";
	String LABEL_BTN_SPECIFY_PATH = "LABEL_BTN_SPECIFY_PATH";
	String LABEL_SPECIFY_PATH = "LABEL_SPECIFY_PATH";
	
	String MSG_DEPLOY_PROGRESS = "MSG_DEPLOY_PROGRESS";
	String MSG_FILE_FAILED = "MSG_FILE_FAILED";
	String MSG_FILE_UPLOADED = "MSG_FILE_UPLOADED";
	String MSG_INVALID_PATH = "MSG_INVALID_PATH";
	
	String TOOLTIP_COPY = "TOOLTIP_COPY";
	String TOOLTIP_CLEAR = "TOOLTIP_CLEAR";
	String TOOLTIP_VALIDATE_PATH = "TOOLTIP_VALIDATE_PATH";
}
