package com.iwebcoding.mobile.tool.constant.nls;

public interface ErrNLS {
	String TITLE_ERR = "TITLE_ERR";
	String TITLE_WARN = "TITLE_WARN";
	String MSG_INIT_LOG = "MSG_INIT_LOG";
	String MSG_PARSE_APPCFG = "MSG_PARSE_APPCFG";
	String MSG_PARSE_SYSCFG = "MSG_PARSE_SYSCFG";
	String MSG_PARSE_ENTCFG = "MSG_PARSE_ENTCFG";
	String MSG_CERT_CHECK = "MSG_CERT_CHECK";
	String MSG_CLOSE_STREAM = "MSG_CLOSE_STREAM";
	String MSG_DOWNLOAD_GROUPCFG = "MSG_DOWNLOAD_GROUPCFG";
	String MSG_INVALID_JSON = "MSG_INVALID_JSON";
	String MSG_READ_JSON = "MSG_READ_JSON";
	String MSG_LOAD_FILE = "MSG_LOAD_FILE";
	String MSG_WRITE_FILE = "MSG_WRITE_FILE";
	String MSG_GEN_CHECKSUM = "MSG_GEN_CHECKSUM";
	String MSG_DRAG_DROP = "MSG_DRAG_DROP";
	String MSG_EXCEED_LIMIT = "MSG_EXCEED_LIMIT";
	String MSG_ZIP_NOT_FOUND = "MSG_ZIP_NOT_FOUND";
	String MSG_DETECT_ZIP = "MSG_DETECT_ZIP";
	String MSG_NOT_FOLDER = "MSG_NOT_FOLDER";
	String MSG_BACKUP_FILE = "MSG_BACKUP_FILE";
	String MSG_REPACE_CHKSUM = "MSG_REPACE_CHKSUM";
}
