package com.iwebcoding.mobile.tool.constant.nls;

public interface JViewerNLS {
	String TITLE_BORDER_VIEWER = "TITLE_BORDER_VIEWER";
	String TITLE_BORDER_CONSOLE = "TITLE_BORDER_CONSOLE";
	
	String TAB_TEXT = "TAB_TEXT";
	String TAB_JSON = "TAB_JSON";
	
	String LABLE_MASTER_JSON = "LABLE_MASTER_JSON";
	
	String CTX_MENU_COPY = "CTX_MENU_COPY";
	String CTX_MENU_EXPORT = "CTX_MENU_EXPORT";
	String CTX_MENU_VERIFY = "CTX_MENU_VERIFY";
	String CTX_MENU_SUBJSON = "CTX_MENU_SUBJSON";
	String CTX_MENU_OPEN = "CTX_MENU_OPEN";
	
	String TOOLTIP_COPY = "TOOLTIP_COPY";
	String TOOLTIP_CLEAR = "TOOLTIP_CLEAR";
	
	String TXT_PASSED = "TXT_PASSED";
	String TXT_FAILED = "TXT_FAILED";
	String TXT_VALID_JSON = "TXT_VALID_JSON";
	
	String VERIFY_PROGRESS = "VERIFY_PROGRESS";
	String ZIP_CONFIG_URL = "ZIP_CONFIG_URL";
	String ZIP_CONFIG_HASHCODE = "ZIP_CONFIG_HASHCODE";
	String ZIP_VERIFY_HASHCODE = "ZIP_VERIFY_HASHCODE";
	String ZIP_VERIFY_RESULT = "ZIP_VERIFY_RESULT";
	String JSON_CONFIG_URL = "JSON_CONFIG_URL";
	String JSON_VERIFY_RESULT = "JSON_VERIFY_RESULT";
}
