package com.iwebcoding.mobile.tool.constant.nls;

public interface SettingNLS {
	String LABEL_PROXY_SERVER = "LABEL_PROXY_SERVER";
	String LABEL_PROXY_PORT = "LABEL_PROXY_PORT";
	String LABEL_NET_TYPE = "LABEL_NET_TYPE";
	String LABEL_DOWNLOAD = "LABEL_DOWNLOAD";
	
	String TITLE_BTN_APPLY = "TITLE_BTN_APPLY";
	String TITLE_BTN_CANCEL = "TITLE_BTN_CANCEL";
	String TITLE_BTN_BROWSE = "TITLE_BTN_BROWSE";
	String TITLE_BTN_CLEAR = "TITLE_BTN_CLEAR";
	String TITLE_BTN_LNF_WEB = "TITLE_BTN_LNF_WEB";
	String TITLE_BTN_LNF_METAL = "TITLE_BTN_LNF_METAL";
	String TITLE_BTN_LNF_SYS = "TITLE_BTN_LNF_SYS";
	String TITLE_BTN_LOCALE_EN = "TITLE_BTN_LOCALE_EN";
	String TITLE_BTN_LOCALE_SC = "TITLE_BTN_LOCALE_SC";
	String TITLE_BTN_LOCALE_TC = "TITLE_BTN_LOCALE_TC";
	String TITLE_BTN_FONT_SANSERIF = "TITLE_BTN_FONT_SANSERIF";
	String TITLE_BTN_FONT_SERIF = "TITLE_BTN_FONT_SERIF";
	String TITLE_BTN_FONT_LISHU = "TITLE_BTN_FONT_LISHU";
	
	String TITLE_WIN = "TITLE_WIN";
	String TITLE_BORDER_WIN = "TITLE_BORDER_WIN";
	String TITLE_BORDER_LNF = "TITLE_BORDER_LNF";
	String TITLE_BORDER_LOCALE = "TITLE_BORDER_LOCALE";
	String TITLE_BORDER_FONT = "TITLE_BORDER_FONT";
	String TITLE_BORDER_NET = "TITLE_BORDER_NET";
	String TITLE_BORDER_DOWNLOAD = "TITLE_BORDER_DOWNLOAD";
	
	String TITLE_TAB_APPERANCE = "TITLE_TAB_APPERANCE";
	String TITLE_TAB_ADVANCED = "TITLE_TAB_ADVANCED";
	
	String MSG_TITLE_WARN = "MSG_TITLE_WARN";
	String MSG_UPDATE_CFG = "MSG_UPDATE_CFG";
}
